_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 477e675f-70eb-4605-925e-1e936ea5b3b9
name: 'Drush Site-Install'
mail: admin@example.com
slogan: 'Awesome platform'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
